GET http://localhost:3007/todos/?priority=HIGH&status=IN%20PROGRESS
###

GET http://localhost:3007/todos/1
###

GET http://localhost:3007/agenda/?date=2000-00-00
###

POST http://localhost:3007/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}
###


PUT http://localhost:3007/todos/2
Content-Type: application/json

{ "status": "DONE" }

###

PUT http://localhost:3007/todos/2
Content-Type: application/json

{ "priority": "AVERAGE" }

###
PUT http://localhost:3007/todos/2
Content-Type: application/json

{
"todo": "Clean the garden"
}

###
PUT http://localhost:3007/todos/2
Content-Type: application/json

{  "category": "LEARNIN" }

###

PUT http://localhost:3007/todos/2
Content-Type: application/json

{ "dueDate": "2021-01-12" }

###


DELETE http://localhost:3007/todos/6

