GET http://localhost:3007/todos/?status=TO%20DO
###

GET http://localhost:3007/todos/1
###

GET http://localhost:3007/agenda/?date=2021-1-12
###

POST http://localhost:3007/todos/
Content-Type: application/json

{
 "id": 6,
 "todo": "Finalize event theme",
 "priority": "LOW",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-02-22"
}
###


PUT http://localhost:3007/todos/2
Content-Type: application/json

{ "status": "DONE" }

###

PUT http://localhost:3007/todos/2
Content-Type: application/json

{ "priority": "HIGH" }

###
PUT http://localhost:3007/todos/2
Content-Type: application/json

{
"todo": "Clean the garden"
}

###
PUT http://localhost:3007/todos/2
Content-Type: application/json

{  "category": "LEARNING" }

###

PUT http://localhost:3007/todos/2
Content-Type: application/json

{ "dueDate": "2021-01-12" }

###


DELETE http://localhost:3007/todos/6

